Repository PandaGuy-blip/2023_S2_-52-_TaskFlow, pull requests merged in 2023-10, with the labels that each got.

#26 Implement Search Feature
  TaskFlow.Tests/ViewModelTests/ToDoViewModelTests.cs
  TaskFlow/App.xaml.cs
  TaskFlow/Model/IDatabase.cs
  TaskFlow/Model/LabelModel.cs
  TaskFlow/Model/TodoModel.cs
  TaskFlow/View/ToDoPage.xaml
  TaskFlow/View/ToDoPage.xaml.cs
  TaskFlow/ViewModel/LabelViewModel.cs
  TaskFlow/ViewModel/NewTodoViewModel.cs
  TaskFlow/ViewModel/SchedulerViewModel.cs
  TaskFlow/ViewModel/ToDoViewModel.cs
Labels: bug, enhancement

#27 Add Filter-By-Label feature to Master
  TaskFlow.Tests/GlobalUsings.cs
  TaskFlow.Tests/ViewModelTests/ToDoViewModelTests.cs
  TaskFlow/CustomControls/CustomSearchBar.cs
  TaskFlow/CustomControls/CustomSearchBarHandler.cs
  TaskFlow/MauiProgram.cs
  TaskFlow/Model/LabelItem.cs
  TaskFlow/Resources/Images/dropdown_icon.svg
  TaskFlow/Resources/Images/search.svg
  TaskFlow/TaskFlow.csproj
  TaskFlow/View/ToDoPage.xaml
  TaskFlow/View/ToDoPage.xaml.cs
  TaskFlow/ViewModel/ToDoViewModel.cs
Labels: enhancement

#28 Notification s2
  TaskFlow/App.xaml.cs
  TaskFlow/MauiProgram.cs
  TaskFlow/Model/Notification.cs
  TaskFlow/Model/NotificationCenterModel.cs
  TaskFlow/Model/TodoItem.cs
  TaskFlow/Platforms/Android/AndroidManifest.xml
  TaskFlow/Platforms/Android/BootReciever.cs
  TaskFlow/Platforms/Android/MainActivity.cs
  TaskFlow/Resources/Images/info_circle.svg
  TaskFlow/TaskFlow.csproj
  TaskFlow/View/Components/TaskReminderComponent.xaml
  TaskFlow/View/Components/TaskReminderComponent.xaml.cs
  TaskFlow/View/Components/TaskReminderComponentDisabled.xaml
  TaskFlow/View/Components/TaskReminderComponentDisabled.xaml.cs
  TaskFlow/View/NewTodoPage.xaml
  TaskFlow/View/ToDoPage.xaml.cs
  TaskFlow/View/TodoPopup.xaml
  TaskFlow/ViewModel/NewTodoViewModel.cs
  TaskFlow/ViewModel/ToDoViewModel.cs
Labels: enhancement, help wanted

#31 Add Achievements feature to Master
  TaskFlow.Tests/ModelTests/AchievementTests.cs
  TaskFlow.Tests/ViewModelTests/ProfileViewModelTests.cs
  TaskFlow.Tests/ViewModelTests/ToDoViewModelTests.cs
  TaskFlow/App.xaml.cs
  TaskFlow/AppShell.xaml
  TaskFlow/AppShell.xaml.cs
  TaskFlow/MauiProgram.cs
  TaskFlow/Messages/ProfileUpdatedMessage.cs
  TaskFlow/Model/Achievement.cs
  TaskFlow/Model/NotificationCenterModel.cs
  TaskFlow/Resources/Images/star_gold.svg
  TaskFlow/Resources/Images/trophy_star.svg
  TaskFlow/TaskFlow.csproj
  TaskFlow/View/DeletePage.xaml.cs
  TaskFlow/View/ProfilePage.xaml
  TaskFlow/View/ProfilePage.xaml.cs
  TaskFlow/ViewModel/DeleteViewModel.cs
  TaskFlow/ViewModel/ProfileViewModel.cs
  TaskFlow/ViewModel/ToDoViewModel.cs
Labels: enhancement
